# Usage sectionn for probot-stale - https://github.com/probot/stale#usage


daysUntilStale: 30


daysUntilClose: 10

onlyLabels: [ "bugs","critical","duplicate","invalid"]


exemptProjects: true


exemptMilestones: false


exemptAssignees: false


staleLabel: action Required


markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

limitPerRun: 5
